### ISSUE TITLE
Hi there - New Issue the Order of Blog posts are always from oldest to newest no matter what

### ISSUE THREAD

**Issue by DLEEXPERT** [ThemeFuse/Brizy#1264]
Since a week or so blog posts are shown in a differnt order! 

from oldest to newest instead of the newest first. No matter what category you choose... or what filter settings no matter if you choose date and ascending or descending!

**Comment by hbouzin** [comment]
> Since a week or so blog posts are shown in a differnt order!
> 
> from oldest to newest instead of the newest first. No matter what category you choose... or what filter settings no matter if you choose date and ascending or descending!

I have the same problem

**Comment by NataliaBB** [comment]
Hello @DLEEXPERT @hbouzin 
The posts order issue has been solved. It will be included in the next release. 
Sorry for the inconveniences.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by hbouzin** [comment]
Hello,

Thank you for your help

I updated to version Version 1.0.70 but the bug is still present for my part

Best regards
