### ISSUE TITLE
Brizy Does not Save Page Updates

### ISSUE THREAD

**Issue by twowheel** [ThemeFuse/Brizy#1309]
Brizy is not saving page updates. Any updates made to pages are simply lost. All occurring post latest update.

**Comment by marianglobalplus** [comment]
i can't either upload any changes in my website. When is it going to be solved?

**Comment by designsbybruno** [comment]
I'm having the same issue. Can't do any changes to my website.. How much longer?

**Comment by squid372** [comment]
having same issue. do updates. cluck update. finishes. go to live page refresh + clear cache and no changes have been done. clients are getting pissed and requesting fines for my account.

**Comment by curiousprojects** [comment]
I just started having the same issue today

**Comment by McScience** [comment]
I'm having the same issue.

**Comment by NataliaBB** [comment]
Hello Everyone! @McScience @curiousprojects @squid372 @designsbybruno @marianglobalplus @twowheel 

Apologizes for the inconveniences. It was a problem with revisions number. We fixed in the upcoming 1.0.75 Brizy version.

Regards, Natalia

**Comment by McScience** [comment]
The version has been upgraded.
However, the changes are still not updated.



감사합니다.
신재욱 올림.

[Logo02]
Email : sjw@mcscience.com<mailto:sjw@mcscience.com>
Mobile : +82-10-6475-1411
Tel : +82-31-303-5776
Fax : +82-31-303-5787

**Comment by NataliaBB** [comment]
@marianglobalplus 
If the update didn't help, please try to increase your php memory limit to 256M. If it also didn't work, send me a ticket on https://support.brizy.io/hc/en-us with your wp credentials.

Thank you!
Regards, Natalia

**Comment by marianglobalplus** [comment]
Good morning,I can't see where i have to write down a ticket. I have updated the version, i already have the 1.0.76 version, and i still can't change anything, changes are not been saved.El 14 de mayo de 2019 a las 13:58 NataliaBB <notifications@github.com> escribió:  @marianglobalplus If the update didn't help, please try to increase your php memory limit to 256M. If it also didn't work, send me a ticket on https://support.brizy.io/hc/en-us with your wp credentials.Thank you! Regards, Natalia—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread. Marian Baena JiménezResponsable de Canales Online693 793 532 / 854 702 588C/ Arquitectura 1, Torre 6, planta 11, módulo 14, 41015 Sevilla (España)theglobalplus.com     |     sirtracking.com

**Comment by squid372** [comment]
issue still persisting on updated version even after memory increase

**Comment by NataliaBB** [comment]
Hi @marianglobalplus @squid372 
In this case, I will need to check the logs and errors from your dashboard. 
Please submit a ticket for me  here: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
