### ISSUE TITLE
Brizy edit not loading, keep spinning in the page

### ISSUE THREAD

**Issue by monamohanty1987** [ThemeFuse/Brizy#1327]
Hi Team,

I am using Brizy to develop my website and i am almost more than halfway.. and now the brizy edit is not loading. Kindly help in this.

Thanks,
Mona

**Comment by dinuionut** [comment]
Hi @monamohanty1987, 

I had this issue recently and it was related to some cached files. Please make sure to clear your CDN or server cache if any (I guess you've already tried clearing your browser cache too).

If this doesn't work, it would help to screenshot the error you see in your Chrome's dev tools console (right click > inspect on the forever loading page).

**Comment by monamohanty1987** [comment]
Hi @dinuionut

Many thanks for the response. I had raised a support ticket in Brizy, they found the issue and they are taking care of it. what is the issue i still dont know but then i tried all option before, nothing worked.


Thanks,
Monalisha

**Comment by NataliaBB** [comment]
Hello @monamohanty1987 @dinuionut 

The issue has been fixed on the 1.0.75 Brizy Version. Please update the plugin and let me know if the editor works.

Thank you!
Regards, Natalia

**Comment by dinuionut** [comment]
@NataliaBB Our client said that it worked after the update, only clearing the CDN cache wasn't enough apparently.

**Comment by AlexandruRaicu** [comment]
@NataliaBB The issue is still happening with a client of us
- He has the last version of the plugin which is 1.0.76
- WordPress 5.2 
![3e80f7439b25d7514d460a9077bca246](https://user-images.githubusercontent.com/15956680/57773347-7f4e2f80-7720-11e9-81c9-38657af0c8cd.png)

**Comment by monamohanty1987** [comment]
Hi Natalia,

Yes it worked after the new plugin. 

Thanks for support.
