### ISSUE TITLE
Woocommerce widgets not shown in sidebar element

### ISSUE THREAD

**Issue by jlconsult** [ThemeFuse/Brizy#1362]
Woocommerce widgets not shown in sidebar element
Wp widgets are shown but Woocommerce filter widgets are not visible

![afbeelding](https://user-images.githubusercontent.com/39246570/58235742-b1bfe400-7d41-11e9-98c3-d90f998cb6bd.png)

![afbeelding](https://user-images.githubusercontent.com/39246570/58235765-bf756980-7d41-11e9-8294-ac38d0c60c77.png)

**Comment by NataliaBB** [comment]
Fixed in the 1.0.77 FREE version.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by jlconsult** [comment]
Hi Natalia,

Still not all widgets are visible,according to me this is not fixed
