### ISSUE TITLE
ISSUE - Form won't submit

### ISSUE THREAD

**Issue by j4media** [ThemeFuse/Brizy#243]
I created a simple form and when I test it in my live environment it does not submit when clicking the submit button.  I think it may have to do with the email field turning 'red' after I put in a legitimate email address.  

I made sure I connected the submit button to the Wordpress plug including the email to send to and the subject for the email.

Please advise on what I may be doing wrong or what the problem may be.

**Comment by arnoldonea** [comment]
Hi, i have the same issue. Is it possible to have this fixed ? it is really important :)

**Comment by bagrinsergiu** [comment]
Hi

Fixed in 1.0.17 - Fixed: Form email field validation

Can you confirm if it is working with last changes?

Thanks

**Comment by arnoldonea** [comment]
No is not. Still show as this . 

Arnold Onea -Sent from my iPhone , while away from office

**Comment by j4media** [comment]
Yes, it is working correctly for me now. 

Thanks.

**Comment by arnoldonea** [comment]
I will thanks, unfortunately i don’t use facebook at all. Any other way please ?!?

Arnold Onea -Sent from my iPhone , while away from office

**Comment by bagrinsergiu** [comment]
Email: sergey.roxigo@gmail.com

**Comment by Massimoivaldi** [comment]
For me it is now working

**Comment by bagrinsergiu** [comment]
Hi @arnoldonea 

Sorry but i don't receive an email with WP credentials.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu
