### ISSUE TITLE
Hyphenation doesn't work correctly on page made with Brizy

### ISSUE THREAD

**Issue by chrisagon** [ThemeFuse/Brizy#399]
Since the last update, the **hyphenation** does not work at all posts and pages made with Brizy.
It is OK with posts published without Brizy :-(  
It is stange : I don't find "hyphen" in the CSS files.

**Comment by bagrinsergiu** [comment]
Hi 

This has been fixed and will be included in the next update. (1.0.21) in ~ 20 hours

 I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Sergiu

**Comment by chrisagon** [comment]
I still have the issue. I have updated brizy => 1.0.22.
I have reopen the page and updated it but the hyphnenation still doesn't work.

**Comment by bagrinsergiu** [comment]
1.0.22 was a hotfix for 21 version. Sorry for the delay but i don't want to add an update (23) before the weekend
