### ISSUE TITLE
No dashes at the end of lines.

### ISSUE THREAD

**Issue by mikes1991** [ThemeFuse/Brizy#404]
After last update, my Firefox has no dashes at the end of lines. It seems that there is some problem with formatting text into a block (also in other browsers like Safari).
![dashes](https://user-images.githubusercontent.com/41758560/43317017-8d1a9380-919b-11e8-991b-50ae7cb91225.jpg)

**Comment by senkelbinder** [comment]
I got the same problem since the last update
no hyphenation /  random partition of words
no dashes

**Comment by bagrinsergiu** [comment]
Hi 

This has been fixed and will be included in the next update. (1.0.21) in ~ 20 hours

 I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Sergiu

**Comment by senkelbinder** [comment]
Hello, it still isn't fixed, even on your own website you got the problem
https://cl.ly/0q0e1Z3B2t0m

**Comment by bagrinsergiu** [comment]
HI @senkelbinder 

Fix was moved for next update planned for Monday (1.0.23)
